baseURL = 'https://automation-gmbh.com/var/www/public/'
languageCode = 'de-DE'
title = 'Automation Steeg und Hoffmeyer GmbH'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 3 
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.de]
    title = "Automation Steeg und Hoffmeyer GmbH"
    weight = 1
    contentDir = "content/de"
    [languages.de.menu]
      [[languages.de.menu.main]]
      name = "Startseite"
      url = "/"
      weight = 1
      [[languages.de.menu.main]]
      name = "Unternehmen"
      url = "/unternehmen/"
      weight = 2
      [[languages.de.menu.main]]
      name = "Kontakt"
      url = "/kontakt/"
      weight = 3
      [[languages.de.menu.main]]
      name = "Impressum"
      url = "/impressum/"
      weight = 4
      [[languages.de.menu.main]]
      name = "Produkte & Leistungen"
      url= "/produkte-und-leistungen/"
      weight = 5
      

  [languages.en]
    title = "Automation Steeg and Hoffmeyer GmbH"
    weight = 2
    contentDir = "content/en"
    [languages.en.menu]
      [[languages.en.menu.main]]
      name = "Home"
      url = "/en/"
      weight = 1
      [[languages.en.menu.main]]
      name = "Company"
      url = "/en/company/"
      weight = 2
      [[languages.en.menu.main]]
      name = "Contact"
      url = "/en/contact"
      weight = 3
    [[languages.en.menu.main]]
      name = "Imprint"
      url = "/en/imprint/"
      weight = 4
    [[languages.en.menu.main]]
    name = "Products & Service"
    url = "/en/products-and-service"
    weight = 5

[params]
  author = "Automation Steeg and Hoffmeyer GmbH"
  site_logo = "images/logo.svg"
  background_color_class = "bg-gary"
  recent_posts_number = 3
  date_format = "2. January 2006"
  custom_css = ["custom.css"]

  custom_fonts = true
  font_myriadpro_regular = "/fonts/MYRIADPRO-REGULAR.woff2"

  
[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/automation-gmbh"
[[params.ananke_socials]]
  name = "linkedin"
  url = "https://de.linkedin.com/company/automation-steeg-und-hoffmeyer-gmbh"
[[params.ananke_socials]]
  name = "youtube"
  url = "https://www.youtube.com/channel/UC66gXpt2kktwbnr06WliRKw"
